### ISSUE TITLE
Any information about the labels?

### ISSUE THREAD

**Issue by RalphMao** [psudowe/parse27k_tools#1]
I would like to know how the labels correspond to the actual attributes. For example, I could see gender attributes are labelled with 0, 1 and 2, but I do not know which stands for male and which stands for N/A. I cannot find it on the doc, so could you provide any further information?

**Comment by psudowe** [comment]
You can find tables for this in the annotation.sqlite3 file.
There is one table for the encoding of each attribute (Gender, Orientation, Orientation8, IsPushing, etc.)

sqlite3 annotation.sqlite3

sqlite> select \* from Gender; 
1|n/a
2|male
3|female

**Comment by RalphMao** [comment]
Thanks! @psudowe
